In [22]:
import pandas as pd
import torch
import torch.nn.functional as F
import numpy as np

import csv
from torch.distributions import Categorical
np.set_printoptions(suppress=True)

In [2]:
import google.colab.drive
google.colab.drive.mount('/content/drive', force_remount=True)

root = '/content/drive/MyDrive/final'

Mounted at /content/drive


In [3]:
df = pd.read_csv(root + '/prob.csv')


In [4]:
df

Unnamed: 0             0  ...           798           799
0                0  2.768213e-13  ...  1.733014e-13  7.750870e-11
1                1  7.153312e-13  ...  1.322831e-09  7.507300e-12
2                2  1.436208e-15  ...  3.750988e-14  1.185937e-19
3                3  3.113767e-11  ...  2.748208e-12  3.309627e-08
4                4  1.755394e-13  ...  3.184044e-13  2.655871e-10
...            ...           ...  ...           ...           ...
511995      511995  3.083856e-13  ...  2.103264e-17  7.566087e-17
511996      511996  1.088731e-07  ...  3.048113e-09  4.323681e-09
511997      511997  2.277237e-07  ...  1.033776e-07  1.096765e-04
511998      511998  7.744804e-05  ...  1.762382e-08  1.691255e-06
511999      511999  3.106074e-08  ...  2.722285e-09  1.920309e-05

[512000 rows x 801 columns]

In [3]:
# prob = torch.tensor(pd.read_csv(root + '/prob.csv').values)
# prob = prob[:,1:]

In [5]:
prob = torch.tensor(df.values)
prob = prob[:,1:]

In [4]:
n_request = 12800

In [36]:
# least confident
least_confident = torch.max(prob, dim=1).values
sorted_lc, index_lc = torch.sort(least_confident)
request_lc = index_lc[:n_request]

In [37]:
print(sorted_lc[:n_request])

tensor([0.0595, 0.0610, 0.0649,  ..., 0.1884, 0.1884, 0.1884],
       dtype=torch.float64)


In [38]:
np.savetxt(root + '/request_least_confident.csv', request_lc.numpy(), delimiter=',')

In [39]:
# margin sampling
sorted_prob, _ = torch.sort(prob, dim=1, descending=True)


In [40]:
ms = sorted_prob[:,0] - sorted_prob[:,1]
ms

tensor([0.8115, 0.3037, 0.9998,  ..., 0.7689, 0.1114, 0.0151],
       dtype=torch.float64)

In [41]:
sorted_ms, index_ms = torch.sort(ms)
request_ms = index_ms[:n_request]


In [12]:
print(sorted_ms[:n_request])

tensor([0.0000e+00, 5.6000e-07, 1.8800e-06,  ..., 1.1641e-02, 1.1643e-02,
        1.1643e-02], dtype=torch.float64)


In [42]:
np.savetxt(root + '/request_margin_sampling.csv', request_ms.numpy(), delimiter=',')

In [ ]:
# entropy v1
# entropy = torch.sum(-prob * torch.log(prob), dim=1)

In [ ]:
# sorted_entropy, index_entropy = torch.sort(entropy, descending=True)

In [7]:
prob.size()

torch.Size([512000, 800])

In [7]:
# entropy v2
entropy1 = Categorical(probs=prob[:256000,:]).entropy()
entropy2 = Categorical(probs=prob[256000:512000,:]).entropy()

In [15]:
entropy = torch.cat((entropy1, entropy2), dim=0)
sorted_entropy, index_entropy = torch.sort(entropy, descending=True)
request_entropy = index_entropy[:n_request]

In [21]:
print(sorted_entropy[0:n_request], request_entropy)
entropy.size()


tensor([4.4953, 4.3971, 4.3707,  ..., 3.0168, 3.0168, 3.0167],
       dtype=torch.float64) tensor([235405, 319481,  11494,  ...,  42202, 477902, 321943])


torch.Size([512000])

In [33]:
print(request_entropy.numpy())

[235405 319481  11494 ...  42202 477902 321943]


In [35]:
np.savetxt(root + '/request_entropy.csv', request_entropy.numpy(), delimiter=',')

In [34]:
# pd.DataFrame(request_entropy.numpy()).to_csv(root + '/request_entropy.csv')