In [ ]:
from google.colab import drive
drive.mount('/content/drive')

/content
sample_data
Mounted at /content/drive


In [ ]:
root='/content/drive/MyDrive/2021 Spring/2572/Final/prob.csv'

In [ ]:
import torch
import torch.nn as nn

import pandas as pd
import numpy as np

print("Loading CSV...")
prob = pd.read_csv(root, encoding = "UTF-8")

print("Converting to Tensor...")
prob_tensor = torch.tensor(prob.to_numpy())
prob_tensor.shape


Loading CSV...
Converting to Tensor...


torch.Size([512000, 801])

In [ ]:
torch.sum(prob_tensor,1)

tensor([1.0000e+00, 2.0000e+00, 3.0000e+00,  ..., 5.1200e+05, 5.1200e+05,
        5.1200e+05], dtype=torch.float64)

In [ ]:
from torch.distributions import Categorical

entropy = Categorical(probs = prob_tensor[:,1:]).entropy()
entropy

tensor([4.5223e-01, 1.4175e+00, 1.0584e-03,  ..., 8.3253e-01, 2.4462e+00,
        2.8300e+00], dtype=torch.float64)

In [ ]:
ids = prob_tensor[:,[0]]

print(ids.shape)
ids

torch.Size([512000, 1])


tensor([[0.0000e+00],
        [1.0000e+00],
        [2.0000e+00],
        ...,
        [5.1200e+05],
        [5.1200e+05],
        [5.1200e+05]], dtype=torch.float64)

In [ ]:
y = torch.unsqueeze(entropy,1)
print(y.shape)
y

torch.Size([512000, 1])


tensor([[4.5223e-01],
        [1.4175e+00],
        [1.0584e-03],
        ...,
        [8.3253e-01],
        [2.4462e+00],
        [2.8300e+00]], dtype=torch.float64)

In [ ]:
out = torch.cat((ids,y),1)
out.shape
out

tensor([[0.0000e+00, 4.5223e-01],
        [1.0000e+00, 1.4175e+00],
        [2.0000e+00, 1.0584e-03],
        ...,
        [5.1200e+05, 8.3253e-01],
        [5.1200e+05, 2.4462e+00],
        [5.1200e+05, 2.8300e+00]], dtype=torch.float64)

In [ ]:
df = pd.DataFrame(out.numpy())
df

<class 'pandas.core.frame.DataFrame'>


In [ ]:
ds = df.sort_values(1,ascending=False)
d = ds.head(12800)[0]

outs = pd.to_numeric(d, downcast='integer')

outs2 = outs.astype(str) + '.png'
outs2.to_csv('request_05.csv',index=False,header=False,line_terminator = ',\n')

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
235405    /dataset/unlabeled/235405.png
319481    /dataset/unlabeled/319481.png
11494      /dataset/unlabeled/11494.png
119154    /dataset/unlabeled/119154.png
231955    /dataset/unlabeled/231955.png
                      ...              
5961        /dataset/unlabeled/5961.png
331696    /dataset/unlabeled/331696.png
42202      /dataset/unlabeled/42202.png
477902    /dataset/unlabeled/477902.png
321943    /dataset/unlabeled/321943.png
Name: 0, Length: 12800, dtype: object
235405    235405.png
319481    319481.png
11494      11494.png
119154    119154.png
231955    231955.png
             ...    
5961        5961.png
331696    331696.png
42202      42202.png
477902    477902.png
321943    321943.png
Name: 0, Length: 12800, dtype: object
